(function(){
  var fallbackSkills=[
    {id:'ux-pro-max',name:'UX Pro Max',category:'前端',tagZh:'前端审美',tagEn:'UI/UX',featured:true,enabled:true,path:'ui-ux-pro-max.txt',github:'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill',descriptionZh:'用于配色、字体、布局、间距、组件层级，把页面从普通提升到高级。',descriptionEn:'Color, typography, spacing, layout and UI quality guidance.',fitZh:'网页美化、视觉升级、UI 规范',fitEn:'UI polish, visual upgrade, design system',sort:1},
    {id:'smart-summarize',name:'Smart Summarize',category:'总结',tagZh:'总结',tagEn:'Summary',featured:false,enabled:true,path:'sum.txt',github:'https://github.com/VanessaPellegrini/skills',descriptionZh:'自动判断内容类型，选择合适的总结方法。',descriptionEn:'Auto-selects the right summarization method.',fitZh:'文章总结、会议纪要、论文提炼',fitEn:'Articles, meetings, papers',sort:2}
  ];
  var skills=fallbackSkills.slice();
  var current=0;
  var view='dashboard';
  var sourceState='正在读取 skills.json';

  function byId(id){return document.getElementById(id)}
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function toast(t){var el=byId('toast');if(!el)return;el.textContent=t;el.className='toast show';setTimeout(function(){el.className='toast'},2600)}
  function selected(){return skills[current]||skills[0]}
  function counts(){var cats={};skills.forEach(function(s){cats[s.category]=(cats[s.category]||0)+1});return {total:skills.length,hot:skills.filter(function(s){return s.featured}).length,on:skills.filter(function(s){return s.enabled!==false}).length,cats:cats}}
  function top(title,desc){return '<section class="top"><div><h1>'+title+'</h1><p>'+desc+'</p><p class="label">数据状态：'+esc(sourceState)+'</p></div><div class="actions"><a class="btn" href="index.html">打开前台</a><input class="pass" id="adminPass" type="password" placeholder="管理密码"><button class="btn publish" id="publishGitHub" type="button">发布到 GitHub</button><button class="btn" id="saveDraft" type="button">保存草稿</button><button class="btn" id="copyJson" type="button">复制 JSON</button><button class="btn primary" id="downloadJson" type="button">导出 JSON</button></div></section>'}
  function metric(label,value){return '<div class="metric"><span>'+label+'</span><b>'+value+'</b></div>'}
  function statsCards(){var c=counts(),n=Object.keys(c.cats).length;return '<section class="grid4">'+metric('技能总数',c.total)+metric('精选技能',c.hot)+metric('分类数量',n)+metric('已启用',c.on)+'</section>'}
  function dashboard(){var recent=skills.slice().sort(function(a,b){return (a.sort||0)-(b.sort||0)}).slice(0,8).map(function(s){return '<tr><td>'+esc(s.name)+'</td><td>'+esc(s.category)+'</td><td><span class="pill '+(s.enabled!==false?'on':'off')+'">'+(s.enabled!==false?'已启用':'已停用')+'</span></td><td>'+esc(s.sort)+'</td></tr>'}).join('');return top('管理后台 · 总览','查看 Skill 库状态，快速进入编辑、分类、统计和发布。')+statsCards()+'<section class="work two"><div class="panel"><h2>最近 Skill</h2><table class="table"><thead><tr><th>名称</th><th>分类</th><th>状态</th><th>排序</th></tr></thead><tbody>'+recent+'</tbody></table></div><div class="panel"><h2>前后端连接</h2><p class="note">前台读取 skills.json。后台点击“发布到 GitHub”会调用 /api/save-skills，把当前数据写回 GitHub 的 skills.json。Vercel 重新部署后，前台就会同步。</p><button class="btn primary" data-go="skills" type="button">进入技能管理</button></div></section>'}
  function renderList(){var kw=byId('kw')?byId('kw').value.toLowerCase():'',cat=byId('cat')?byId('cat').value:'全部';var html='';skills.forEach(function(s,i){var hay=JSON.stringify(s).toLowerCase();var ok=(!kw||hay.indexOf(kw)>-1)&&(cat==='全部'||s.category===cat);if(!ok)return;html+='<div class="row '+(i===current?'active':'')+'" data-i="'+i+'"><strong>'+esc(s.name)+'</strong><div class="meta"><span class="pill">'+esc(s.category)+'</span><span class="pill '+(s.enabled!==false?'on':'off')+'">'+(s.enabled!==false?'已启用':'已停用')+'</span><span class="pill">'+(s.featured?'精选':'普通')+'</span><span class="pill">排序 '+esc(s.sort)+'</span></div></div>'});var el=byId('list');if(el)el.innerHTML=html||'<div class="empty">没有匹配结果</div>';Array.prototype.forEach.call(document.querySelectorAll('.row[data-i]'),function(r){r.onclick=function(){current=Number(r.getAttribute('data-i'));render()}})}
  function field(k,label,type){var s=selected();if(type==='textarea')return '<label class="full">'+label+'<textarea data-k="'+k+'">'+esc(s[k])+'</textarea></label>';if(type==='check')return '<label><input type="checkbox" data-k="'+k+'" '+(s[k]?'checked':'')+'> '+label+'</label>';return '<label '+(k==='github'||k==='path'?'class="full"':'')+'>'+label+'<input data-k="'+k+'" value="'+esc(s[k])+'"></label>'}
  function renderPreview(){var s=selected(),el=byId('preview');if(!el)return;if(!s){el.innerHTML='';return}el.innerHTML='<div class="card-preview"><div class="num">'+String(s.sort||0).padStart(2,'0')+'</div><span>'+esc(s.tagZh)+'</span><h3>'+esc(s.name)+'</h3><p>'+esc(s.descriptionZh)+'</p><p class="fit">适合：'+esc(s.fitZh)+'</p><div class="mockbtns"><i>一键复制</i><i>打开查看</i><i>GitHub 原版</i></div></div>'}
  function skillView(){return top('技能管理','搜索、筛选、编辑、预览 Skill。发布后前台读取新的 skills.json。')+'<section class="work"><div class="panel"><h2>Skill 列表</h2><div class="toolbar"><input id="kw" placeholder="搜索名称、分类、用途"><select id="cat"><option>全部</option><option>总结</option><option>前端</option><option>设计</option><option>MCP</option><option>测试</option><option>品牌</option></select></div><div class="actions small-actions"><button class="btn primary" id="add" type="button">+ 添加技能</button><button class="btn danger" id="remove" type="button">删除当前</button></div><div class="list" id="list"></div></div><div class="panel"><h2>编辑技能</h2><div class="form" id="form"></div></div><aside class="preview"><h2>实时预览</h2><div id="preview"></div><p class="note">编辑后先保存草稿，再输入管理密码发布到 GitHub。</p></aside></section>'}
  function renderForm(){var s=selected(),el=byId('form');if(!el)return;if(!s){el.innerHTML='暂无数据';return}el.innerHTML=field('name','技能名称')+field('category','分类')+field('tagZh','中文标签')+field('tagEn','英文标签')+field('descriptionZh','中文简介','textarea')+field('descriptionEn','英文简介','textarea')+field('fitZh','适合任务','textarea')+field('fitEn','英文适合任务','textarea')+field('path','本站规则链接')+field('github','GitHub 原版链接')+field('sort','排序')+'<div class="checks full">'+field('featured','设为精选','check')+field('enabled','启用','check')+'</div>';Array.prototype.forEach.call(document.querySelectorAll('[data-k]'),function(el){el.oninput=el.onchange=function(){var s=selected(),k=el.getAttribute('data-k');if(el.type==='checkbox')s[k]=el.checked;else if(k==='sort')s[k]=Number(el.value)||0;else s[k]=el.value;renderList();renderPreview()}})}
  function categories(){var c=counts().cats;var html=Object.keys(c).map(function(k){var pct=skills.length?Math.round(c[k]/skills.length*100):0;return '<div class="cat-card"><b>'+esc(k)+'</b><p>'+c[k]+' 个 Skill</p><div class="bar"><i style="width:'+Math.max(8,pct)+'%"></i></div></div>'}).join('');return top('分类管理','查看当前分类数量。后续可以增加分类新增、改名、合并功能。')+'<section class="cat-grid">'+html+'</section><section class="notice">建议固定分类：总结、前端、设计、MCP、测试、品牌。不要太多，否则小白更难选。</section>'}
  function statsView(){var c=counts().cats;var rows=Object.keys(c).map(function(k){var pct=skills.length?Math.round(c[k]/skills.length*100):0;return '<tr><td>'+esc(k)+'</td><td>'+c[k]+'</td><td><div class="bar"><i style="width:'+pct+'%"></i></div></td><td>'+pct+'%</td></tr>'}).join('');var top5=skills.slice().sort(function(a,b){return (a.sort||0)-(b.sort||0)}).slice(0,5).map(function(s,i){return '<tr><td>'+(i+1)+'</td><td>'+esc(s.name)+'</td><td>'+esc(s.category)+'</td><td>'+(s.featured?'精选':'普通')+'</td></tr>'}).join('');return top('数据统计','当前是静态统计。后续接入接口后，可以统计复制次数和访问量。')+statsCards()+'<section class="work two"><div class="panel"><h2>分类占比</h2><table class="table"><tbody>'+rows+'</tbody></table></div><div class="panel"><h2>Skill 排名预览</h2><table class="table"><tbody>'+top5+'</tbody></table></div></section>'}
  function settings(){return top('系统设置','管理发布方式、GitHub Token 接入计划和安全提示。')+'<section class="work two"><div class="panel"><h2>当前发布方式</h2><p class="note">后台现在可以调用 /api/save-skills 发布到 GitHub。发布前必须在 Vercel 环境变量里配置 GITHUB_TOKEN 和 ADMIN_PASSWORD。</p><button class="btn primary" id="downloadJson2" type="button">导出当前 JSON</button></div><div class="panel"><h2>需要配置的环境变量</h2><p class="note">GITHUB_TOKEN：GitHub 个人访问令牌，需要仓库 contents 写入权限。<br>ADMIN_PASSWORD：你自己设置的后台发布密码。<br>可选：GITHUB_REPO、GITHUB_BRANCH、SKILLS_FILE_PATH。</p></div></section><section class="notice">安全提醒：不要把 GitHub Token 填在网页里，只能放在 Vercel 环境变量中。</section>'}
  function addSkill(){skills.push({id:'new-skill-'+Date.now(),name:'新技能',category:'前端',tagZh:'标签',tagEn:'Tag',featured:false,enabled:true,path:'new-skill.txt',github:'https://github.com/',descriptionZh:'这里填写技能简介。',descriptionEn:'Skill description.',fitZh:'适合任务',fitEn:'Best for',sort:skills.length+1});current=skills.length-1;render();toast('已添加新技能')}
  function removeSkill(){if(!skills.length)return;if(confirm('确定删除当前技能吗？')){skills.splice(current,1);current=Math.max(0,current-1);render();toast('已删除')}}
  function json(){return JSON.stringify(skills,null,2)}
  function download(){var blob=new Blob([json()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='skills.json';a.click();URL.revokeObjectURL(a.href);toast('已导出 skills.json')}
  function copyJson(){if(navigator.clipboard)navigator.clipboard.writeText(json()).then(function(){toast('JSON 已复制')}).catch(download);else download()}
  function saveDraft(){localStorage.setItem('skillhub-admin-draft',json());toast('草稿已保存在浏览器')}
  function publishGitHub(){var pass=byId('adminPass');var password=pass?pass.value:'';if(!password){toast('请先输入管理密码');return}toast('正在发布到 GitHub...');fetch('/api/save-skills',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:password,skills:skills})}).then(function(r){return r.json().then(function(data){return {ok:r.ok,data:data}})}).then(function(x){if(!x.ok||!x.data.ok)throw new Error(x.data.message||'发布失败');localStorage.removeItem('skillhub-admin-draft');sourceState='已发布到 GitHub，等待 Vercel 自动部署';render();toast('发布成功，等待 Vercel 自动部署')}).catch(function(e){toast('发布失败：'+(e.message||e))})}
  function bindCommon(){if(byId('saveDraft'))byId('saveDraft').onclick=saveDraft;if(byId('copyJson'))byId('copyJson').onclick=copyJson;if(byId('downloadJson'))byId('downloadJson').onclick=download;if(byId('downloadJson2'))byId('downloadJson2').onclick=download;if(byId('publishGitHub'))byId('publishGitHub').onclick=publishGitHub;Array.prototype.forEach.call(document.querySelectorAll('[data-go]'),function(b){b.onclick=function(){view=b.getAttribute('data-go');render()}})}
  function render(){Array.prototype.forEach.call(document.querySelectorAll('#nav button'),function(b){b.classList.toggle('active',b.getAttribute('data-view')===view)});var main=byId('main');if(view==='dashboard')main.innerHTML=dashboard();if(view==='skills')main.innerHTML=skillView();if(view==='categories')main.innerHTML=categories();if(view==='stats')main.innerHTML=statsView();if(view==='settings')main.innerHTML=settings();bindCommon();if(view==='skills'){renderList();renderForm();renderPreview();byId('add').onclick=addSkill;byId('remove').onclick=removeSkill;byId('kw').oninput=renderList;byId('cat').onchange=renderList}}
  function boot(){Array.prototype.forEach.call(document.querySelectorAll('#nav button'),function(b){b.onclick=function(){view=b.getAttribute('data-view');render()}});render();fetch('skills.json?ts='+Date.now()).then(function(r){if(!r.ok)throw new Error('skills.json '+r.status);return r.json()}).then(function(data){var draft=localStorage.getItem('skillhub-admin-draft');skills=draft?JSON.parse(draft):(Array.isArray(data)?data:fallbackSkills.slice());sourceState=draft?'已读取浏览器草稿':'已连接 skills.json';render();if(draft)toast('已读取浏览器草稿')}).catch(function(){sourceState='读取 skills.json 失败，正在使用内置备用数据';skills=fallbackSkills.slice();render();toast('skills.json 读取失败，已显示备用数据')})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
