(function(){
  const fallbackSkills=[
    {id:'ux-pro-max',name:'UX Pro Max',category:'前端',tagZh:'前端审美',tagEn:'UI/UX',featured:true,enabled:true,path:'ui-ux-pro-max.txt',github:'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill',descriptionZh:'用于配色、字体、布局、间距、组件层级，把页面从普通提升到高级。',descriptionEn:'Color, typography, spacing, layout and UI quality guidance.',fitZh:'网页美化、视觉升级、UI 规范',fitEn:'UI polish, visual upgrade, design system',sort:1},
    {id:'einui-liquid-glass',name:'Ein UI / Liquid Glass React',category:'前端',tagZh:'液态玻璃',tagEn:'Liquid Glass',featured:true,enabled:true,path:'einui-liquid-glass.txt',github:'https://github.com/unobtuse/einui-claude-skill',descriptionZh:'用于设计 React / Next.js 的 Liquid Glass 玻璃拟态组件、卡片、按钮和高级后台界面。',descriptionEn:'Liquid glass UI components, cards, buttons and premium admin interfaces.',fitZh:'玻璃拟态、后台美化、React UI、Next.js 页面',fitEn:'Glassmorphism, admin UI, React UI, Next.js pages',sort:2}
  ];
  const cats=['全部','前端','设计','文档','测试','MCP','效率','多模态','其他'];
  let skills=fallbackSkills.slice(),current=0,view='dashboard',sourceState='正在读取数据库',health=null,autoTimer=null,autoState='自动发布已开启';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const toast=t=>{const el=$('toast');if(!el)return;el.textContent=t;el.className='toast show';setTimeout(()=>el.className='toast',2600)};
  const selected=()=>skills[current]||skills[0];
  const json=()=>JSON.stringify(skills,null,2);
  const adminToken=()=>sessionStorage.getItem('skillhub-admin-token')||'';
  function normalizeCat(c){if(['总结','文档','PDF','PPT','OCR'].includes(c))return '文档';if(['品牌','效率'].includes(c))return '效率';if(['图片','图像','视频','多模态'].includes(c))return '多模态';if(cats.includes(c))return c;return '其他'}
  function counts(){const map={};skills.forEach(s=>{const c=normalizeCat(s.category);map[c]=(map[c]||0)+1});return {total:skills.length,hot:skills.filter(s=>s.featured).length,on:skills.filter(s=>s.enabled!==false).length,cats:map}}
  function top(title,desc){return `<section class="top"><div><h1>${title}</h1><p>${desc}</p><p class="label">数据状态：${esc(sourceState)} ｜ ${esc(autoState)}</p></div><div class="actions"><a class="btn" href="import-save.html">导入 / 重新检测</a><a class="btn" href="setup.html">配置向导</a><a class="btn" href="index.html">打开前台</a><input class="pass" id="adminPass" type="password" placeholder="手动密码可选"><button class="btn publish" id="publishDb" type="button">立即发布</button><button class="btn" id="saveDraft" type="button">保存草稿</button><button class="btn" id="reloadOnline" type="button">重载线上</button><button class="btn" id="copyJson" type="button">复制 JSON</button><button class="btn primary" id="downloadJson" type="button">导出 JSON</button></div></section>`}
  function metric(label,value){return `<div class="metric"><span>${label}</span><b>${value}</b></div>`}
  function statsCards(){const c=counts();return `<section class="grid4">${metric('技能总数',c.total)}${metric('精选技能',c.hot)}${metric('分类数量',Object.keys(c.cats).length)}${metric('已启用',c.on)}</section>`}
  function healthPanel(){if(!health)return `<section class="notice" style="margin-top:16px">正在检查 Supabase 状态...</section>`;const missing=(health.missing||[]).join('、')||'无';return `<section class="notice" style="margin-top:16px"><b>数据库检查：</b>${health.supabaseConfigured?'环境变量已配置':'还缺环境变量：'+missing}。${health.canReadSupabase?'skills 表可读取。':'如果还没建表，请打开“配置向导”复制 SQL。'}</section>`}
  function dashboard(){const recent=skills.slice().sort((a,b)=>(a.sort||0)-(b.sort||0)).slice(0,8).map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(normalizeCat(s.category))}</td><td><span class="pill ${s.enabled!==false?'on':'off'}">${s.enabled!==false?'已启用':'已停用'}</span></td><td>${esc(s.sort)}</td></tr>`).join('');return top('管理后台 · 总览','已开启自动发布。导入页现在支持“先分析预览，再确认保存 / 更新”。')+statsCards()+healthPanel()+`<section class="work two"><div class="panel"><h2>最近 Skill</h2><table class="table"><thead><tr><th>名称</th><th>分类</th><th>状态</th><th>排序</th></tr></thead><tbody>${recent}</tbody></table></div><div class="panel"><h2>导入和重新检测</h2><p class="note">想新增仓库，点“导入 / 重新检测”。想重新检测当前 Skill，在技能管理里点“重新检测当前”。</p><a class="btn primary" href="import-save.html">打开导入检测页</a></div></section>`}
  function skillView(){return top('技能管理','添加、编辑、预览 Skill。修改后会自动发布到 Supabase，前台刷新即可生效。')+`<section class="work"><div class="panel"><h2>Skill 列表</h2><div class="toolbar"><input id="kw" placeholder="搜索名称、分类、用途"><select id="cat">${cats.map(c=>`<option>${c}</option>`).join('')}</select></div><div class="actions small-actions"><button class="btn primary" id="add" type="button">+ 添加技能</button><button class="btn" id="recheck" type="button">重新检测当前</button><button class="btn danger" id="remove" type="button">删除当前</button></div><div class="list" id="list"></div></div><div class="panel"><h2>编辑技能</h2><div class="form" id="form"></div></div><aside class="preview"><h2>实时预览</h2><div id="preview"></div><p class="note">“重新检测当前”会把当前 Skill 的 GitHub 链接带到导入页，先分析预览，确认后再更新。</p></aside></section>`}
  function renderList(){const kw=($('kw')?.value||'').toLowerCase(),cat=$('cat')?.value||'全部';let html='';skills.forEach((s,i)=>{const hay=JSON.stringify(s).toLowerCase();if((kw&&hay.indexOf(kw)<0)||(cat!=='全部'&&normalizeCat(s.category)!==cat))return;html+=`<div class="row ${i===current?'active':''}" data-i="${i}"><strong>${esc(s.name)}</strong><div class="meta"><span class="pill">${esc(normalizeCat(s.category))}</span><span class="pill ${s.enabled!==false?'on':'off'}">${s.enabled!==false?'已启用':'已停用'}</span><span class="pill">${s.featured?'精选':'普通'}</span><span class="pill">排序 ${esc(s.sort)}</span></div></div>`});$('list').innerHTML=html||'<div class="empty">没有匹配结果</div>';document.querySelectorAll('.row[data-i]').forEach(r=>r.onclick=()=>{current=Number(r.dataset.i);render()})}
  function field(k,label,type){const s=selected();if(type==='textarea')return `<label class="full">${label}<textarea data-k="${k}">${esc(s[k])}</textarea></label>`;if(type==='check')return `<label><input type="checkbox" data-k="${k}" ${s[k]?'checked':''}> ${label}</label>`;return `<label ${['id','path','github'].includes(k)?'class="full"':''}>${label}<input data-k="${k}" value="${esc(s[k])}"></label>`}
  function renderForm(){const s=selected(),el=$('form');if(!el)return;if(!s){el.innerHTML='暂无数据';return}el.innerHTML=field('id','唯一 ID')+field('name','技能名称')+field('category','分类')+field('tagZh','中文标签')+field('tagEn','英文标签')+field('descriptionZh','中文简介','textarea')+field('descriptionEn','英文简介','textarea')+field('fitZh','适合任务','textarea')+field('fitEn','英文适合任务','textarea')+field('path','本站规则链接')+field('github','GitHub 原版链接')+field('sort','排序')+`<div class="checks full">${field('featured','设为精选','check')}${field('enabled','启用','check')}</div>`;document.querySelectorAll('[data-k]').forEach(el=>el.oninput=el.onchange=()=>{const k=el.dataset.k;if(el.type==='checkbox')s[k]=el.checked;else if(k==='sort')s[k]=Number(el.value)||0;else s[k]=el.value;renderList();renderPreview();queueAutoPublish()})}
  function renderPreview(){const s=selected(),el=$('preview');if(!el||!s)return;el.innerHTML=`<div class="card-preview"><div class="num">${String(s.sort||0).padStart(2,'0')}</div><span>${esc(s.tagZh)}</span><h3>${esc(s.name)}</h3><p>${esc(s.descriptionZh)}</p><p class="fit">适合：${esc(s.fitZh)}</p><div class="mockbtns"><i>一键复制</i><i>打开查看</i><i>GitHub 原版</i></div></div>`}
  function categories(){const c=counts().cats;return top('分类管理','查看当前分类数量。')+`<section class="cat-grid">${Object.keys(c).map(k=>`<div class="cat-card"><b>${esc(k)}</b><p>${c[k]} 个 Skill</p><div class="bar"><i style="width:${Math.max(8,Math.round(c[k]/skills.length*100))}%"></i></div></div>`).join('')}</section><section class="notice">固定分类：前端、设计、文档、测试、MCP、效率、多模态、其他。</section>`}
  function statsView(){const c=counts().cats;const rows=Object.keys(c).map(k=>{const pct=skills.length?Math.round(c[k]/skills.length*100):0;return `<tr><td>${esc(k)}</td><td>${c[k]}</td><td><div class="bar"><i style="width:${pct}%"></i></div></td><td>${pct}%</td></tr>`}).join('');return top('数据统计','当前是 Skill 静态统计，后续可加复制次数和热门排行。')+statsCards()+`<section class="panel" style="margin-top:16px"><h2>分类占比</h2><table class="table"><tbody>${rows}</tbody></table></section>`}
  function settings(){return top('系统设置','管理 Supabase 数据库、发布密码和安全提示。')+healthPanel()+`<section class="work two"><div class="panel"><h2>自动发布</h2><p class="note">当前已开启自动发布。你登录后台后，新增、删除、修改 Skill 会自动写入 Supabase。</p></div><div class="panel"><h2>需要的环境变量</h2><p class="note">SUPABASE_URL<br>SUPABASE_SERVICE_ROLE_KEY<br>ADMIN_PASSWORD</p></div></section>`}
  function addSkill(){skills.push({id:'new-skill-'+Date.now(),name:'新技能',category:'前端',tagZh:'标签',tagEn:'Tag',featured:false,enabled:true,path:'new-skill.txt',github:'https://github.com/',descriptionZh:'这里填写技能简介。',descriptionEn:'Skill description.',fitZh:'适合任务',fitEn:'Best for',sort:skills.length+1});current=skills.length-1;render();toast('已添加新技能，准备自动发布');queueAutoPublish()}
  function removeSkill(){if(!skills.length)return;if(confirm('确定删除当前技能吗？')){skills.splice(current,1);current=Math.max(0,current-1);render();toast('已删除，准备自动发布');queueAutoPublish()}}
  function recheckSkill(){const s=selected();if(!s)return toast('没有可检测的 Skill');const url=s.github&&s.github!=='#'?s.github:s.path;location.href='import-save.html?url='+encodeURIComponent(url||'')}
  function download(){const blob=new Blob([json()],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='skills.json';a.click();URL.revokeObjectURL(a.href);toast('已导出 skills.json')}
  function copyJson(){navigator.clipboard?navigator.clipboard.writeText(json()).then(()=>toast('JSON 已复制')).catch(download):download()}
  function saveDraft(){localStorage.setItem('skillhub-admin-draft',json());toast('草稿已保存在浏览器')}
  function queueAutoPublish(){clearTimeout(autoTimer);autoState='等待自动发布...';autoTimer=setTimeout(()=>publishDb(true),1500)}
  function publishDb(silent){const password=$('adminPass')?.value||'';const token=adminToken();if(!token&&!password){toast('登录已过期，请重新登录');setTimeout(()=>location.href='login.html',900);return}if(!silent)toast('正在发布到 Supabase...');autoState=silent?'正在自动发布...':'正在发布...';fetch('/api/save-skills-db',{method:'POST',headers:{'Content-Type':'application/json','X-Admin-Token':token},body:JSON.stringify({password,token,skills})}).then(r=>r.json().then(data=>({ok:r.ok,data}))).then(x=>{if(!x.ok||!x.data.ok)throw new Error(x.data.message||'发布失败');localStorage.removeItem('skillhub-admin-draft');sourceState='已发布到 Supabase，前台刷新即可生效';autoState='自动发布成功';if(silent)toast('已自动保存到 Supabase');else{render();toast('发布成功，前台刷新即可生效')}}).catch(e=>{autoState='自动发布失败';toast('发布失败：'+(e.message||e))})}
  function bindCommon(){if($('saveDraft'))$('saveDraft').onclick=saveDraft;if($('reloadOnline'))$('reloadOnline').onclick=()=>{localStorage.removeItem('skillhub-admin-draft');sourceState='正在重新读取线上数据';render();loadData(false)};if($('copyJson'))$('copyJson').onclick=copyJson;if($('downloadJson'))$('downloadJson').onclick=download;if($('publishDb'))$('publishDb').onclick=()=>publishDb(false);document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{view=b.dataset.go;render()})}
  function render(){try{document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const main=$('main');if(view==='dashboard')main.innerHTML=dashboard();if(view==='skills')main.innerHTML=skillView();if(view==='categories')main.innerHTML=categories();if(view==='stats')main.innerHTML=statsView();if(view==='settings')main.innerHTML=settings();bindCommon();if(view==='skills'){renderList();renderForm();renderPreview();$('add').onclick=addSkill;$('remove').onclick=removeSkill;$('recheck').onclick=recheckSkill;$('kw').oninput=renderList;$('cat').onchange=renderList}}catch(e){$('main').innerHTML=`<section class="notice">后台脚本错误：${esc(e.message||e)}</section>`;console.error(e)}}
  function normalizeRows(data){return Array.isArray(data)?data:[]}
  function loadJsonFallback(){return fetch('skills.json?ts='+Date.now()).then(r=>r.json()).then(data=>{skills=normalizeRows(data);current=0;sourceState='Supabase 未配置，已读取 skills.json 备用数据';render()})}
  function loadData(useDraft){fetch('/api/skills?ts='+Date.now()).then(r=>r.json().then(data=>({ok:r.ok,data}))).then(x=>{if(!x.ok||!x.data.ok)throw new Error(x.data.message||'Supabase not ready');const draft=useDraft?localStorage.getItem('skillhub-admin-draft'):null;let parsed=null;if(draft){try{parsed=JSON.parse(draft)}catch(e){localStorage.removeItem('skillhub-admin-draft')}}skills=parsed||normalizeRows(x.data.skills);current=0;sourceState=parsed?'已读取浏览器草稿':(x.data.source==='json-fallback'?'已读取 JSON 备用数据，等待自动写入 Supabase':'已连接 Supabase 实时数据库');render();if(parsed)toast('已读取草稿，修改后会自动发布')}).catch(()=>loadJsonFallback().catch(()=>{skills=fallbackSkills.slice();sourceState='数据库和 JSON 都失败，使用备用数据';render()}))}
  function checkHealth(){fetch('/api/health?ts='+Date.now()).then(r=>r.json()).then(d=>{health=d;render()}).catch(()=>{health={missing:['检查失败'],supabaseConfigured:false,canReadSupabase:false};render()})}
  function boot(){document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;render()});render();loadData(true);checkHealth()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
