(function(){
var lang=localStorage.getItem('lang')||'zh',cat='全部',q='',skills=[],source='loading',stats=loadStats();
var catsZh=['全部','前端','设计','文档','测试','MCP','效率','多模态','其他'];
var ui={zh:{title:'AI Skill 调用入口管理器',sub:'不用翻 GitHub，不用记复杂提示词。选择一个 Skill，复制稳定调用话术，让 ChatGPT 按规则帮你干活。',line:'每个 Skill 都保留固定版本规则链接和 GitHub 原版来源，适合小白直接复制使用。',badge:'稳定 · 可追溯 · 一键复制',flow:'选择 Skill → 一键复制调用话术 → 粘贴给 ChatGPT → 让 AI 读取规则并执行任务。',featured:'推荐使用',all:'全部 Skill',why:'为什么用它',open:'打开规则',copy:'一键复制',github:'GitHub 原版',copied:'已复制调用话术，可以粘贴给 ChatGPT 使用',lang:'中文 / EN',preview:'三步调用',search:'搜索 Skill / 任务关键词',fit:'适合：',trust:'本站只整理公开 Skill 的稳定调用入口，原始内容归对应 GitHub 仓库所有。',empty:'没有找到匹配的 Skill',loading:'正在读取数据库...',admin:'管理后台',task:'请在这里粘贴你的具体任务。',hot:'本机热门 Skill',cats:catsZh,advantages:[['稳定入口','导入时尽量固定到 GitHub commit 版本，降低原仓库改动导致链接失效的概率。'],['调用更规范','复制出来不是普通链接，而是包含 Skill 名称、规则链接、执行要求和任务占位的严格话术。'],['适合小白使用','不用找 SKILL.md，不用翻仓库，打开官网就能选 Skill、复制、粘贴给 AI。'],['可持续扩展','后台可继续导入 GitHub 仓库主页，自动整理成可调用 Skill 卡片。']]},en:{title:'AI Skill Launcher',sub:'No GitHub digging, no prompt memorization. Pick a Skill, copy a stable prompt, and let ChatGPT follow the rule.',line:'Each Skill keeps a pinned rule link and the original GitHub source for traceability.',badge:'Stable · Traceable · One-click copy',flow:'Choose a Skill → copy strict prompt → paste into ChatGPT → let AI read the rule and execute.',featured:'Recommended',all:'All Skills',why:'Why use it',open:'Open rule',copy:'Copy',github:'GitHub source',copied:'Prompt copied. Paste it into ChatGPT.',lang:'EN / 中文',preview:'Three-step launch',search:'Search Skills or task keywords',fit:'Best for: ',trust:'This site organizes stable entry points for public Skill rules. Original content belongs to the corresponding GitHub repositories.',empty:'No matching Skill found',loading:'Loading database...',admin:'Admin',task:'Paste your task here.',hot:'Local popular Skills',cats:['All','Frontend','Design','Docs','Testing','MCP','Productivity','Multimodal','Other'],advantages:[['Stable entry','Imports try to pin GitHub commit versions to reduce link breakage from future repository changes.'],['Strict prompt copy','The copy button includes Skill name, rule link, requirements, and a task placeholder.'],['Beginner friendly','No need to find SKILL.md manually. Pick, copy, and paste into your AI tool.'],['Easy to expand','Import GitHub repository URLs in the admin console and turn them into Skill cards.']]} };
function T(k){return ui[lang][k]}function safe(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function loadStats(){try{return JSON.parse(localStorage.getItem('skillhub-copy-stats')||'{}')}catch(e){return {}}}
function saveStats(){localStorage.setItem('skillhub-copy-stats',JSON.stringify(stats))}
function recordCopy(id,name){id=id||name||'unknown';stats[id]=stats[id]||{id:id,name:name||id,count:0};stats[id].name=name||stats[id].name;stats[id].count=(stats[id].count||0)+1;saveStats()}
function normalizeCategory(c){if(['总结','文档','PDF','PPT','OCR'].indexOf(c)>-1)return '文档';if(['品牌','效率'].indexOf(c)>-1)return '效率';if(['图片','图像','视频','多模态'].indexOf(c)>-1)return '多模态';if(catsZh.indexOf(c)>-1)return c;return '其他'}
function cname(c){var n=normalizeCategory(c);if(lang==='en'){var m={全部:'All',前端:'Frontend',设计:'Design',文档:'Docs',测试:'Testing',MCP:'MCP',效率:'Productivity',多模态:'Multimodal',其他:'Other'};return m[n]||n}return n}
function item(s){var tag=lang==='zh'?s.tagZh:s.tagEn,desc=lang==='zh'?s.descriptionZh:s.descriptionEn,fit=lang==='zh'?s.fitZh:s.fitEn;return '<article class="card"><div class="num">'+String(s.sort||0).padStart(2,'0')+'</div><span>'+safe(tag)+'</span><h3>'+safe(s.name)+'</h3><p>'+safe(desc)+'</p><p class="fit">'+T('fit')+safe(fit)+'</p><div class="btns"><button data-copy="'+safe(s.path)+'" data-id="'+safe(s.id)+'">'+T('copy')+'</button><a href="'+safe(s.path)+'" target="_blank" rel="noopener">'+T('open')+'</a><a class="source" target="_blank" rel="noopener" href="'+safe(s.github)+'">'+T('github')+'</a></div></article>'}
function visible(){var needle=q.trim().toLowerCase();return skills.filter(function(s){var sc=normalizeCategory(s.category);var ok=(s.enabled!==false)&&(cat==='全部'||sc===cat);var hay=Object.keys(s).map(function(k){return s[k]}).join(' ').toLowerCase();return ok&&(!needle||hay.indexOf(needle)>-1)}).sort(function(a,b){return (a.sort||0)-(b.sort||0)})}
function controls(){return '<section class="controls"><input id="search" placeholder="'+T('search')+'" value="'+safe(q)+'"><div class="filters">'+catsZh.map(function(c){return '<button class="filter '+(cat===c?'active':'')+'" data-cat="'+c+'">'+cname(c)+'</button>'}).join('')+'</div></section>'}
function promptText(name,url){return '请读取下面这个 Skill 规则链接，并严格按照里面的流程处理我的任务。\n\nSkill 名称：'+name+'\n规则链接：'+url+'\n\n执行要求：\n1. 必须先读取完整规则内容，不要凭记忆或自行发挥。\n2. 必须按照 Skill 中定义的流程、方法、输出格式执行。\n3. 如果无法读取链接或规则不完整，必须明确说明失败原因。\n4. 在正式处理任务前，先说明将使用哪个 Skill，以及为什么使用它。\n5. 输出内容必须和我的任务相关，不要只复述规则。\n\n我的任务：\n'+T('task')}
function adv(){return '<section class="advantages"><div><em>'+T('why')+'</em><h2>'+T('why')+'</h2></div>'+ui[lang].advantages.map(function(a){return '<article><b>'+safe(a[0])+'</b><p>'+safe(a[1])+'</p></article>'}).join('')+'</section>'}
function grid(){var v=visible();if(!v.length)return '<section class="empty">'+T('empty')+'</section>';var fs=v.filter(function(s){return s.featured}).map(item).join('');var all=v.filter(function(s){return !s.featured}).map(item).join('');return (fs?'<h2>'+T('featured')+'</h2><section class="grid featured">'+fs+'</section>':'')+(all?'<h2>'+T('all')+'</h2><section class="grid">'+all+'</section>':'')}
function updateList(){var list=document.getElementById('list');if(!list)return;list.classList.remove('list-animating');list.innerHTML=grid();void list.offsetWidth;list.classList.add('list-animating')}
function statsSection(){var arr=Object.keys(stats).map(function(k){return stats[k]}).sort(function(a,b){return (b.count||0)-(a.count||0)}).slice(0,5);if(!arr.length)return '';return '<section class="advantages"><div><em>'+T('hot')+'</em><h2>'+T('hot')+'</h2></div>'+arr.map(function(x,i){return '<article><b>#'+(i+1)+' '+safe(x.name)+'</b><p>复制 '+safe(x.count)+' 次</p></article>'}).join('')+'</section>'}
function statusText(){return source==='supabase'?'Supabase 实时数据库':source==='json'?'JSON 备用数据':'Loading'}
function render(){document.body.innerHTML='<header class="nav"><div class="logo"><i></i><b>SkillHub</b></div><div class="nav-actions"><a class="admin-link" href="admin.html">'+T('admin')+'</a><button id="lang">'+T('lang')+'</button></div></header><main><section class="hero"><div><em>'+T('badge')+'</em><h1>'+T('title')+'</h1><p>'+T('sub')+'</p><p class="tagline">'+T('line')+'</p><div class="chips"><span>Copy</span><span>'+statusText()+'</span><span>Source</span></div></div><aside><b>'+T('preview')+'</b><pre>① '+T('copy')+'\n② '+T('open')+'\n③ '+T('github')+'</pre></aside></section><section class="flow">'+T('flow')+'</section>'+adv()+statsSection()+controls()+'<div id="list">'+(skills.length?grid():'<section class="empty">'+T('loading')+'</section>')+'</div><footer>'+T('trust')+'</footer><div id="toast"></div></main>';bind()}
function toast(msg){var el=document.getElementById('toast');el.textContent=msg;el.className='show';setTimeout(function(){el.className=''},2200)}
function copyFeedback(b,card){var old=b.textContent;b.classList.add('copied');b.textContent=lang==='zh'?'已复制 ✓':'Copied ✓';if(card){card.classList.remove('flash');void card.offsetWidth;card.classList.add('flash')}setTimeout(function(){b.classList.remove('copied');b.textContent=old},1600)}
function bind(){document.getElementById('lang').onclick=function(){lang=lang==='zh'?'en':'zh';localStorage.setItem('lang',lang);render()};var search=document.getElementById('search');if(search)search.oninput=function(e){q=e.target.value;updateList()};document.querySelectorAll('.filter').forEach(function(b){b.onclick=function(){cat=b.dataset.cat;document.querySelectorAll('.filter').forEach(function(x){x.classList.remove('active')});b.classList.add('active');updateList()}})}
function loadJsonFallback(){return fetch('skills.json?ts='+Date.now()).then(function(r){return r.json()}).then(function(data){skills=Array.isArray(data)?data:[];source='json';render()})}
function loadSkills(){fetch('/api/skills?ts='+Date.now()).then(function(r){return r.json().then(function(data){return {ok:r.ok,data:data}})}).then(function(x){if(!x.ok||!x.data.ok)throw new Error(x.data.message||'Supabase not ready');skills=Array.isArray(x.data.skills)?x.data.skills:[];source=x.data.source==='supabase'?'supabase':'json';render()}).catch(function(){loadJsonFallback().catch(function(){skills=[];source='json';render()})})}
document.addEventListener('click',function(e){var b=e.target.closest('button[data-copy]');if(!b)return;var card=b.closest('.card');var name=card.querySelector('h3').textContent;var id=b.dataset.id||name;var url=new URL(b.dataset.copy,location.href).href;var s=promptText(name,url);navigator.clipboard.writeText(s).then(function(){recordCopy(id,name);copyFeedback(b,card);toast(T('copied'))}).catch(function(){recordCopy(id,name);copyFeedback(b,card);prompt(T('copy'),s)})});
render();loadSkills();
})();
