(function(){
var lang=localStorage.getItem('lang')||'zh';
var ui={zh:{title:'AI Skill 导航台',sub:'把优秀 Skill 变成一个可复制、可查看、可追溯原版的工作流官网。默认中文，适合直接发给 ChatGPT / Claude / Codex 使用。',badge:'Liquid Glass Skill 工作流',flow:'选择 Skill → 一键复制调用话术 → 打开查看规则 → 必要时回到 GitHub 原版核对。',featured:'推荐使用',all:'更多 Skill',why:'我们的优势',open:'打开查看',copy:'一键复制',github:'GitHub 原版',copied:'已复制',lang:'中文 / EN',preview:'三按钮工作流',task:'请在这里粘贴你的具体任务。',advantages:[['原文可追溯','每个 Skill 都保留 GitHub 原版入口，避免规则被改写后说不清来源。'],['调用更规范','复制出来不是普通链接，而是包含 Skill 名称、规则链接、执行要求和任务占位的严格话术。'],['适合小白使用','不用记命令，不用翻仓库，打开官网就能选 Skill、复制、粘贴给 AI。'],['可持续扩展','后续可以继续加入前端、设计、MCP、图片、OCR、PPT 等不同类型 Skill。']]},en:{title:'AI Skill Console',sub:'A liquid-glass workspace for reusable AI Skills with copy, preview, and original GitHub traceability.',badge:'Liquid Glass Skill Workflow',flow:'Choose a Skill → copy strict prompt → open local rule → verify original GitHub source when needed.',featured:'Recommended',all:'More Skills',why:'Why this site',open:'Open rule',copy:'Copy',github:'GitHub source',copied:'Copied',lang:'EN / 中文',preview:'Three-button workflow',task:'Paste your task here.',advantages:[['Traceable source','Every Skill keeps a GitHub source link so the original rule is easy to verify.'],['Strict prompt copy','The copy button includes Skill name, rule link, requirements, and a task placeholder.'],['Beginner friendly','No command memorization. Pick a Skill, copy, and paste into your AI tool.'],['Easy to expand','More Skills can be added later for frontend, design, MCP, OCR, slides, and images.']]} };
var cards=[
['featured','01','前端审美','UI/UX','UX Pro Max','ui-ux-pro-max.txt','https://github.com/nextlevelbuilder/ui-ux-pro-max-skill/blob/65e23199492fa911af32d9078e627ab4de01f4c8/.claude/skills/ui-ux-pro-max/SKILL.md','用于配色、字体、布局、间距、组件层级，把页面从普通提升到高级。','Color, typography, spacing, layout and UI quality guidance.'],
['featured','02','界面打磨','Polish','Impeccable','impeccable.txt','https://github.com/ninehills/skills/blob/f3e82a7e2bfbed54fc2b4a715a1986f5f467e827/impeccable/SKILL.md','用于审查、改进、修复和验证页面细节，适合反复打磨网站。','Audit, improve, fix and verify frontend UI details.'],
['featured','03','动效组件','React','React Bits','react-bits.txt','https://github.com/lumacoder/react-bits-skills/blob/3999649c0f7b39c1e13db8732bca85722784ea7d/SKILL.md','用于生成动效组件、Hero 区域、卡片交互和高级落地页代码。','Animated components, hero sections and landing-page code.'],
['featured','04','代码原则','Coding','Karpathy Guide','karpathy-guidelines.txt','https://github.com/multica-ai/andrej-karpathy-skills/blob/2c606141936f1eeef17fa3043a72095b4765b9c2/skills/karpathy-guidelines/SKILL.md','让 AI 写代码前先思考，少乱改、少过度设计、改动更精准。','Think first, keep it simple, and make surgical code changes.'],
['all','05','总结','Summary','Smart Summarize','sum.txt','https://github.com/VanessaPellegrini/skills/blob/0ce3f9a52600c72a76dbc22a9e8d0b640702de87/learning/smart-summarize/auto/SKILL.md','自动判断内容类型，选择合适的总结方法。','Auto-selects the right summarization method.'],
['all','06','视觉设计','Design','Frontend Design','frontend-design.txt','https://github.com/anthropics/skills/blob/57546260929473d4e0d1c1bb75297be2fdfa1949/skills/frontend-design/SKILL.md','生成更有辨识度的网页和应用界面。','Creates distinctive web and app interfaces.'],
['all','07','测试调试','Testing','Webapp Testing','webapp-testing.txt','https://github.com/anthropics/skills/blob/57546260929473d4e0d1c1bb75297be2fdfa1949/skills/webapp-testing/SKILL.md','网页测试、截图、日志检查和交互调试。','Web testing, screenshots, logs and interactions.'],
['all','08','MCP','MCP','MCP Builder','mcp-builder.txt','https://github.com/anthropics/skills/blob/57546260929473d4e0d1c1bb75297be2fdfa1949/skills/mcp-builder/SKILL.md','创建 MCP 服务，把外部工具接入 AI Agent。','Build MCP servers for AI agents.'],
['all','09','海报视觉','Canvas','Canvas Design','canvas-design.txt','https://github.com/anthropics/skills/blob/57546260929473d4e0d1c1bb75297be2fdfa1949/skills/canvas-design/SKILL.md','海报、静态视觉、艺术画面和设计风格生成。','Posters, art direction and visual design.'],
['all','10','品牌规范','Brand','Brand Guidelines','brand-guidelines.txt','https://github.com/anthropics/skills/blob/57546260929473d4e0d1c1bb75297be2fdfa1949/skills/brand-guidelines/SKILL.md','统一品牌色、字体、排版和视觉规范。','Brand colors, typography and layout rules.'],
['all','11','复杂前端','React','Web Artifacts Builder','web-artifacts-builder.txt','https://github.com/anthropics/skills/blob/57546260929473d4e0d1c1bb75297be2fdfa1949/skills/web-artifacts-builder/SKILL.md','复杂前端原型、React、Tailwind 和组件化界面。','Complex React and Tailwind prototypes.']
];
function T(k){return ui[lang][k]}function safe(s){return String(s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function card(x){var tag=lang==='zh'?x[2]:x[3],desc=lang==='zh'?x[7]:x[8];return '<article class="card"><div class="num">'+x[1]+'</div><span>'+safe(tag)+'</span><h3>'+safe(x[4])+'</h3><p>'+safe(desc)+'</p><div class="btns"><button data-copy="'+safe(x[5])+'">'+T('copy')+'</button><a href="'+safe(x[5])+'">'+T('open')+'</a><a class="source" target="_blank" rel="noopener" href="'+safe(x[6])+'">'+T('github')+'</a></div></article>'}
function promptText(name,url){return '请读取下面这个 Skill 规则链接，并严格按照里面的流程处理我的任务。\n\nSkill 名称：'+name+'\n规则链接：'+url+'\n\n执行要求：\n1. 必须先读取完整规则内容，不要凭记忆或自行发挥。\n2. 必须按照 Skill 中定义的流程、方法、输出格式执行。\n3. 如果无法读取链接或规则不完整，必须明确说明失败原因。\n4. 在正式处理任务前，先说明将使用哪个 Skill，以及为什么使用它。\n5. 输出内容必须和我的任务相关，不要只复述规则。\n\n我的任务：\n'+T('task')}
function adv(){return '<section class="advantages"><div><em>'+T('why')+'</em><h2>'+T('why')+'</h2></div>'+ui[lang].advantages.map(function(a){return '<article><b>'+safe(a[0])+'</b><p>'+safe(a[1])+'</p></article>'}).join('')+'</section>'}
function render(){var fs=cards.filter(function(x){return x[0]=='featured'}).map(card).join('');var all=cards.filter(function(x){return x[0]=='all'}).map(card).join('');document.body.innerHTML='<header class="nav"><div class="logo"><i></i><b>SkillHub</b></div><button id="lang">'+T('lang')+'</button></header><main><section class="hero"><div><em>'+T('badge')+'</em><h1>'+T('title')+'</h1><p>'+T('sub')+'</p><div class="chips"><span>Copy</span><span>Preview</span><span>Source</span></div></div><aside><b>'+T('preview')+'</b><pre>① '+T('copy')+'\n② '+T('open')+'\n③ '+T('github')+'</pre></aside></section><section class="flow">'+T('flow')+'</section>'+adv()+'<h2>'+T('featured')+'</h2><section class="grid featured">'+fs+'</section><h2>'+T('all')+'</h2><section class="grid">'+all+'</section></main>';document.getElementById('lang').onclick=function(){lang=lang==='zh'?'en':'zh';localStorage.setItem('lang',lang);render()}}
document.addEventListener('click',function(e){var b=e.target.closest('button[data-copy]');if(!b)return;var name=b.closest('.card').querySelector('h3').textContent;var url=new URL(b.dataset.copy,location.href).href;var s=promptText(name,url);navigator.clipboard.writeText(s).then(function(){var o=b.textContent;b.textContent=T('copied');setTimeout(function(){b.textContent=o},1200)}).catch(function(){prompt(T('copy'),s)})});
render();
})();